version: '2'
networks: 
    dev:
volumes: 
    data-peer:
    data-orderer:
    data-ca:
    data-couchdb:
services: 
    peer:
        extends: 
            file: peer-base.yaml
            service: peer-base
        container_name: devpeer
        environment: 
            - CORE_PEER_ID=devpeer
            - CORE_PEER_ADDRESS=devpeer:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_LOCALMSPID=Org1MSP

            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
        volumes: 
            - ./crypto-config/peerOrganizations/org1.com/peers/devpeer:/peer
            - data-peer:/var/hyperledger/production
        depends_on: 
            - couchdb
        networks: 
            - dev
    cli:
        container_name: cli
        image: hyperledger/fabric-tools:latest
        tty: true
        stdin_open: true
        environment: 
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=devpeer:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_MSPCONFIGPATH=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/msp
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/ca.crt
        volumes: 
            - ./crypto-config:/crypto-config
            - ./channel-artifacts:/channel-artifacts
            - /var/run/:/host/var/run/
            - ../chaincode:/opt/gopath/src/chaincode
        networks: 
            - dev
    orderer:
        container_name: orderer
        extends: 
            file: peer-base.yaml
            service: orderer-base
        environment: 
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        volumes: 
            - ./channel-artifacts:/channel-artifacts
            - ./crypto-config/ordererOrganizations/orderer.com/orderers/orderer:/orderer
            - data-orderer:/var/hyperledger/production/orderer
        ports: 
            - 7050:7050
        networks: 
            - dev
    ca:
        container_name: devca
        extends: 
            file: peer-base.yaml
            service: ca-base
        environment: 
            - FABRIC_CA_SERVER_CA_NAME=devca
        volumes: 
            - ./crypto-config/peerOrganizations/org1.com/ca:/ca
            - data-ca:/etc/hyperledger/fabric-ca-server
        ports: 
            - 7054:7054
        networks: 
            - dev
    couchdb:
        extends: 
            file: peer-base.yaml
            service: couchdb
        container_name: couchdb
        volumes: 
            - data-couchdb:/opt/couchdb
        ports: 
            - 5984:5984
        networks: 
            - dev

