version: '2'
networks: 
    dev:
volumes: 
    data-peer:
services: 
    peer:
        extends: 
            file: peer-base.yaml
            service: peer-base
        container_name: devpeer
        environment: 
            - CORE_PEER_ID=devpeer
            - CORE_PEER_ADDRESS=devpeer:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        volumes: 
            - ./crypto-config/peerOrganizations/org1.com/peers/devpeer:/peer
            - data-peer:/var/hyperledger/production
        networks: 
            - dev
    cli:
        image: hyperledger/fabric-tools:latest
        tty: true
        stdin_open: true
        environment: 
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=devpeer:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_MSPCONFIGPATH=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/msp
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/ca.crt
        volumes: 
            - ./crypto-config:/crypto-config
            - ./channel-artifacts:/channel-artifacts
            - /var/run/:/host/var/run/
        networks: 
            - dev

