version: '2'
services: 
    peer-base:
        image: hyperledger/fabric-peer:latest
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_MSPCONFIGPATH=/peer/msp
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            #- CORE_PEER_TLS_ENABLED=false
            #- CORE_PEER_TLS_CERT_FILE=/peer/tls/server.crt
            #- CORE_PEER_TLS_KEY_FILE=/peer/tls/server.key
            #- CORE_PEER_TLS_ROOTCERT_FILE=/peer/tls/ca.crt
        volumes: 
            - /var/run/:/host/var/run/
        command: peer node start